# -*- coding: utf-8 -*-
"""nexusgen_supply_chain_v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQVLmvMqzwsUABMDh8HzjSXocz-zwllD
"""

# =============================================================================
# NexusGen: Gen-AI Supply Chain Oracle  ── VERSION 2.0
# Fokus: Prediksi suku cadang truk berat & optimasi stok korporat
# ─────────────────────────────────────────────────────────────────────────────
# [DATA]   48 bulan (dari 36), 8 parts (dari 5), distribusi Negative Binomial
#          (lebih realistis dari Poisson untuk demand intermittent)
# [FCST]   Prophet (Meta) sebagai metode utama; HGB sebagai alternatif kuat;
#          Croston SBA dipertahankan sebagai baseline check
#          → ensemble Prophet(0.6) + HGB(0.4) jika keduanya tersedia
# [INV]    Dynamic Safety Stock: variance lead time diperhitungkan
#          ABC-XYZ classification otomatis per part
#          EOQ dinamis dengan holding cost berbasis unit cost
# [RISK]   Risk Score 0-100 dengan breakdown: demand uncertainty + inventory gap
#          + criticality weighting (CRITICAL/HIGH/MEDIUM)
# [AI]     Claude API (Anthropic) menggantikan Gemini
#          Prompt diperkaya dengan ABC-XYZ, Pareto, multi-dimensional risk
# [VIZ]    Dashboard 10 panel (v1: 4 panel) dengan ABC analysis & risk matrix
# =============================================================================

from __future__ import annotations

import argparse
import json
import os
import warnings
from dataclasses import dataclass, field
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.ensemble import HistGradientBoostingRegressor

warnings.filterwarnings("ignore")

!pip install scikit-learn scipy pandas numpy matplotlib
!pip install prophet
!pip install anthropic


# ─────────────────────────────────────────────────────────────────
# KONFIGURASI
# ─────────────────────────────────────────────────────────────────

@dataclass
class NexusConfig:
    n_months: int = 48                  # dari 36 → 48 bulan
    forecast_horizon: int = 6           # dari 3 → 6 bulan
    lead_time_default: int = 2
    service_level_default: float = 0.97 # dari 0.95 → 0.97
    holding_cost_pct: float = 0.22
    order_cost_idr: float = 750_000     # dari 500k → 750k
    claude_model: str = "claude-sonnet-4-20250514"
    anthropic_api_key: str = field(
        default_factory=lambda: os.getenv("ANTHROPIC_API_KEY", ""))
    output_dir: Path = Path("nexusgen_output")

    def __post_init__(self):
        self.output_dir.mkdir(parents=True, exist_ok=True)


CFG = NexusConfig()


# Katalog suku cadang diperluas (v1: 5 parts → v2: 8 parts)
SPARE_PARTS_CATALOG: dict[str, dict] = {
    "Filter Oli HD":          {"base_prob": 0.45, "base_qty": 6,  "unit_cost": 85_000,   "criticality": "HIGH"},
    "Kampas Rem Besar":       {"base_prob": 0.30, "base_qty": 4,  "unit_cost": 320_000,  "criticality": "HIGH"},
    "Pompa Injeksi Lama":     {"base_prob": 0.18, "base_qty": 2,  "unit_cost": 1_200_000,"criticality": "CRITICAL"},
    "Gasket Kepala Silinder": {"base_prob": 0.22, "base_qty": 5,  "unit_cost": 450_000,  "criticality": "MEDIUM"},
    "Bearing Differential":   {"base_prob": 0.12, "base_qty": 2,  "unit_cost": 780_000,  "criticality": "HIGH"},
    "V-Belt Kompressor":      {"base_prob": 0.35, "base_qty": 8,  "unit_cost": 95_000,   "criticality": "MEDIUM"},
    "Seal Kit Hidrolik":      {"base_prob": 0.20, "base_qty": 3,  "unit_cost": 230_000,  "criticality": "MEDIUM"},
    "Relay Control Unit":     {"base_prob": 0.08, "base_qty": 1,  "unit_cost": 2_100_000,"criticality": "CRITICAL"},
}


# ─────────────────────────────────────────────────────────────────
# MODUL 1: SIMULASI DATA HISTORIS (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def generate_intermittent_demand_data(
    n_months: int = CFG.n_months,
    seed: int = 42,
) -> pd.DataFrame:
    """
    [UPGRADE v2] Data demand 48 bulan (dari 36), 8 parts (dari 5).
    - Distribusi Negative Binomial menggantikan Poisson
      (lebih realistis untuk demand intermittent dengan over-dispersion)
    - Seasonal pattern 2 puncak (Q4 + Q3) menggantikan 1 puncak (Q4 saja)
    - Tren non-linear (logistik) menggantikan tren linear
    - Tambah kolom: unit_cost, criticality, quarter
    """
    np.random.seed(seed)
    date_range = pd.date_range(start="2021-01-01", periods=n_months, freq="MS")
    records: list[dict] = []

    for part_name, params in SPARE_PARTS_CATALOG.items():
        for i, date in enumerate(date_range):
            # Dua musim puncak (baru)
            seasonal_boost = (
                1.9 if date.month in [11, 12, 1] else   # Q4/awal tahun
                1.4 if date.month in [6, 7, 8]  else    # pertengahan tahun (baru)
                1.0
            )
            # Tren logistik (lebih realistis dari linear)
            trend_factor = 1 + 0.35 / (1 + np.exp(-0.15 * (i - n_months / 2)))

            prob = min(params["base_prob"] * seasonal_boost * trend_factor, 0.97)
            demand_occurs = np.random.binomial(1, prob)

            if demand_occurs:
                # Negative Binomial – lebih over-dispersed dari Poisson (baru)
                expected_qty = params["base_qty"] * seasonal_boost
                r = max(1, int(expected_qty))
                p_nb = r / (r + expected_qty)
                qty = int(np.random.negative_binomial(r, p_nb)) + 1
            else:
                qty = 0

            records.append({
                "date":        date,
                "part_name":   part_name,
                "demand":      qty,
                "month":       date.month,
                "year":        date.year,
                "quarter":     date.quarter,
                "unit_cost":   params["unit_cost"],
                "criticality": params["criticality"],
                "seasonal_factor": round(seasonal_boost, 2),
            })

    df = pd.DataFrame(records)
    print("✅ Dataset Intermittent Demand berhasil dibuat.")
    print(f"   Periode  : {df['date'].min().strftime('%b %Y')} – "
          f"{df['date'].max().strftime('%b %Y')} ({n_months} bulan)")
    print(f"   Parts    : {df['part_name'].nunique()} (v1: 5)")
    print(f"   Records  : {len(df):,}")
    print(f"   Distribusi qty: Negative Binomial (v1: Poisson)\n")
    return df


def describe_data_quality(df: pd.DataFrame) -> pd.DataFrame:
    """Ringkasan kualitas data per part."""
    return (
        df.groupby("part_name")["demand"]
        .agg(["count", "sum", "mean", "std", "nunique"])
        .rename(columns={"count": "records", "sum": "total_demand",
                         "mean": "avg_demand", "std": "std_demand",
                         "nunique": "unique_values"})
        .reset_index()
    )


# ─────────────────────────────────────────────────────────────────
# MODUL 2: ADVANCED FORECASTING (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def forecast_demand(
    demand_series: np.ndarray,
    dates: pd.DatetimeIndex,
    horizon: int = CFG.forecast_horizon,
) -> dict:
    """
    [UPGRADE v2] Metode forecast diprioritaskan:
    1. Prophet (Meta) – jika tersedia (pip install prophet)
       Unggulan untuk data musiman & intermittent
    2. HGB Gradient Boosting dengan lag features yang diperkaya
       (Menggantikan lstm_forecast yang sebelumnya hanya alias HGB)
    3. Croston SBA – dipertahankan sebagai sanity check / baseline

    Jika Prophet tersedia → ensemble Prophet(0.6) + HGB(0.4)
    Jika tidak → HGB saja (tetap jauh lebih baik dari Croston sendiri)
    """
    series = np.asarray(demand_series, dtype=float)

    # ── Metode 1: Prophet ──
    prophet_forecast = None
    try:
        from prophet import Prophet
        df_p = pd.DataFrame({"ds": dates, "y": series})
        m = Prophet(
            yearly_seasonality=True,
            weekly_seasonality=False,
            daily_seasonality=False,
            seasonality_mode="multiplicative",
            changepoint_prior_scale=0.05,
            interval_width=0.80,
        )
        m.fit(df_p, iter=300)
        future = m.make_future_dataframe(periods=horizon, freq="MS")
        fc = m.predict(future)
        prophet_forecast = {
            "mean":  np.maximum(0, fc["yhat"].values[-horizon:]),
            "lower": np.maximum(0, fc["yhat_lower"].values[-horizon:]),
            "upper": np.maximum(0, fc["yhat_upper"].values[-horizon:]),
        }
    except ImportError:
        pass
    except Exception as e:
        print(f"   ⚠️  Prophet error: {e}")

    # ── Metode 2: HGB dengan lag features diperkaya ──
    n_lag = min(12, len(series) // 2)
    if len(series) >= n_lag + 2:
        feat_df = pd.DataFrame({"demand": series})
        for lag in range(1, n_lag + 1):
            feat_df[f"lag_{lag}"] = feat_df["demand"].shift(lag)
        feat_df["trend"]     = np.arange(len(feat_df), dtype=float)
        feat_df["month"]     = (np.arange(len(feat_df)) % 12) + 1
        feat_df["quarter"]   = ((np.arange(len(feat_df)) % 12) // 3) + 1
        feat_df["sin_month"] = np.sin(2 * np.pi * feat_df["month"] / 12)
        feat_df["cos_month"] = np.cos(2 * np.pi * feat_df["month"] / 12)
        feat_df["roll3_mean"] = feat_df["demand"].shift(1).rolling(3).mean()
        feat_df["roll6_mean"] = feat_df["demand"].shift(1).rolling(6).mean()
        feat_df = feat_df.dropna().reset_index(drop=True)

        feat_cols = [c for c in feat_df.columns if c != "demand"]
        model = HistGradientBoostingRegressor(
            max_iter=400, learning_rate=0.05,
            max_leaf_nodes=24, l2_regularization=0.2, random_state=42,
        )
        model.fit(feat_df[feat_cols].values, feat_df["demand"].values)

        last_window = list(series[-n_lag:])
        hgb_preds: list[float] = []
        for step in range(horizon):
            t   = float(len(series) + step)
            m_v = float((len(series) + step) % 12 + 1)
            q_v = float(((len(series) + step) % 12) // 3 + 1)
            r3  = float(np.mean(last_window[-3:])) if len(last_window) >= 3 else float(np.mean(last_window))
            r6  = float(np.mean(last_window[-6:])) if len(last_window) >= 6 else float(np.mean(last_window))
            feats = (last_window[-n_lag:]
                     + [t, m_v, q_v,
                        np.sin(2 * np.pi * m_v / 12),
                        np.cos(2 * np.pi * m_v / 12),
                        r3, r6])
            pred = float(max(0, model.predict(np.array(feats).reshape(1, -1))[0]))
            hgb_preds.append(pred)
            last_window.append(pred)
        hgb_forecast = np.array(hgb_preds)
    else:
        hgb_forecast = np.full(horizon, float(series.mean()))

    # ── Croston SBA (baseline) ──
    croston_next = _croston_sba(series)

    # ── Ensemble ──
    if prophet_forecast is not None:
        ensemble = 0.6 * prophet_forecast["mean"] + 0.4 * hgb_forecast
        method = "Prophet(0.6) + HGB(0.4)"
        lower  = prophet_forecast["lower"]
        upper  = prophet_forecast["upper"]
    else:
        ensemble = hgb_forecast
        method   = "HGB Boosting (install Prophet untuk hasil lebih akurat: pip install prophet)"
        std_fc   = hgb_forecast.std() * 0.5
        lower    = np.maximum(0, hgb_forecast - std_fc)
        upper    = hgb_forecast + std_fc

    return {
        "ensemble_forecast": np.maximum(0, ensemble),
        "hgb_forecast":      hgb_forecast,
        "prophet_forecast":  prophet_forecast,
        "croston_next":      croston_next,
        "lower_bound":       lower,
        "upper_bound":       upper,
        "method":            method,
        "horizon":           horizon,
    }


def _croston_sba(demand: np.ndarray, alpha: float = 0.1) -> float:
    """Croston SBA – dipertahankan sebagai baseline check."""
    demand = np.asarray(demand, dtype=float)
    nz = np.where(demand > 0)[0]
    if len(nz) == 0:
        return 0.0
    a_t = demand[nz].mean()
    p_t = float(np.diff(np.concatenate(([-1], nz))).mean())
    for i, d in enumerate(demand):
        if d > 0:
            a_t = alpha * d + (1 - alpha) * a_t
            p_t = alpha * max(1, i) + (1 - alpha) * p_t
    return float((1 - alpha / 2) * a_t / max(p_t, 1e-6))


# backward-compat alias (agar kode lama tetap jalan)
def crostons_method(demand_series, alpha=0.1, variant="sba"):
    demand = np.asarray(demand_series, dtype=float)
    fc_next = _croston_sba(demand, alpha)
    return {"next_forecast": fc_next, "variant": variant}


# ─────────────────────────────────────────────────────────────────
# MODUL 3: DYNAMIC INVENTORY PLANNING (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def calculate_safety_stock(
    demand_series: np.ndarray,
    part_name: str = "",
    unit_cost: float = 0.0,
    criticality: str = "MEDIUM",
    lead_time_months: int = CFG.lead_time_default,
    service_level: float = CFG.service_level_default,
) -> dict:
    """
    [UPGRADE v2] Dynamic Safety Stock dengan:
    - Variance lead time diperhitungkan (v1 mengabaikan)
    - ABC-XYZ classification otomatis
    - Service level disesuaikan criticality (CRITICAL=99%, HIGH=97%, MEDIUM=95%)
    - EOQ dinamis berbasis unit cost sebenarnya
    - Annual holding cost dihitung eksplisit
    """
    demand = np.asarray([d for d in demand_series if d >= 0], dtype=float)
    if len(demand) == 0:
        demand = np.array([1.0])

    # Service level berbasis criticality (baru)
    sl_map = {"CRITICAL": 0.99, "HIGH": 0.97, "MEDIUM": 0.95}
    adj_sl = sl_map.get(criticality, service_level)
    Z = float(stats.norm.ppf(adj_sl))

    mean_d = float(demand.mean())
    std_d  = float(demand.std()) if len(demand) > 1 else 0.5
    cv     = std_d / (mean_d + 1e-9)

    # XYZ Classification (baru)
    xyz = "X" if cv < 0.5 else "Y" if cv < 1.0 else "Z"

    # ABC Classification berdasarkan nilai (baru, approx)
    annual_value = mean_d * 12 * unit_cost
    abc = ("A" if annual_value > 5_000_000 else
           "B" if annual_value > 1_000_000 else "C")

    # Dynamic SS: variance demand + variance lead time (baru)
    std_lt   = lead_time_months * 0.2  # asumsi std LT = 20% dari mean
    ss_demand = Z * std_d * np.sqrt(lead_time_months)
    ss_lt     = Z * mean_d * std_lt
    safety_stock = int(np.ceil(np.sqrt(ss_demand**2 + ss_lt**2)))
    safety_stock = max(1, safety_stock)

    rop = int(np.ceil(mean_d * lead_time_months + safety_stock))

    # EOQ dinamis berbasis unit cost (baru)
    annual_demand = mean_d * 12
    h = (unit_cost * CFG.holding_cost_pct) if unit_cost > 0 else 50_000
    eoq = int(np.ceil(np.sqrt(2 * annual_demand * CFG.order_cost_idr / (h + 1e-9))))
    eoq = max(1, eoq)

    # Biaya tahunan
    annual_holding = (safety_stock + eoq / 2) * h
    inventory_value_at_rop = rop * unit_cost

    return {
        "part_name":             part_name,
        "criticality":           criticality,
        "abc_class":             abc,
        "xyz_class":             xyz,
        "service_level_pct":     f"{adj_sl*100:.0f}%",
        "Z":                     round(Z, 4),
        "mean_demand":           round(mean_d, 2),
        "std_demand":            round(std_d, 3),
        "cv":                    round(cv, 3),
        "lead_time":             lead_time_months,
        "safety_stock":          safety_stock,
        "reorder_point":         rop,
        "eoq":                   eoq,
        "annual_holding_cost_idr": int(annual_holding),
        "inventory_value_idr":   int(inventory_value_at_rop),
        "stockout_risk_pct":     f"{(1-adj_sl)*100:.1f}%",
        "unit_cost":             int(unit_cost),
    }


def generate_service_level_scenarios(
    demand_series: np.ndarray,
    unit_cost: float = 0,
    criticality: str = "MEDIUM",
    lead_time_months: int = CFG.lead_time_default,
) -> dict[int, dict]:
    return {
        sl: calculate_safety_stock(demand_series, unit_cost=unit_cost,
                                   criticality=criticality,
                                   lead_time_months=lead_time_months,
                                   service_level=sl / 100)
        for sl in [90, 95, 97, 99]
    }


# ─────────────────────────────────────────────────────────────────
# MODUL 4: RISK SCORING (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def compute_risk_score(
    current_stock: int,
    inventory_plan: dict,
    forecast_result: dict,
) -> dict:
    """
    [UPGRADE v2] Risk Score multi-dimensi (0–100) dengan breakdown.
    - v1: satu angka sederhana berbasis ROP gap saja
    - v2: Inventory Gap + Demand Uncertainty + Criticality Weight
    """
    ss  = inventory_plan["safety_stock"]
    rop = inventory_plan["reorder_point"]
    crit = inventory_plan["criticality"]

    crit_w = {"CRITICAL": 1.5, "HIGH": 1.2, "MEDIUM": 1.0}.get(crit, 1.0)
    stock_ratio = current_stock / (rop + 1e-9)

    # Inventory Risk
    inv_risk = int(np.clip(max(0, (1 - stock_ratio) * 60)
                           * crit_w + (15 if current_stock <= ss else 0), 0, 100))

    # Demand Uncertainty Risk
    fc = forecast_result["ensemble_forecast"]
    cv_fc = float(np.std(fc) / (np.mean(fc) + 1e-9))
    demand_risk = int(np.clip(cv_fc * 80, 0, 100))

    # Coverage Risk (stok habis dalam berapa bulan)
    avg_fc = float(np.mean(fc))
    months_cover = current_stock / (avg_fc + 1e-9)
    cover_risk = int(np.clip(max(0, (3 - months_cover) / 3 * 60) * crit_w, 0, 100))

    composite = int(0.40 * inv_risk + 0.30 * demand_risk + 0.30 * cover_risk)
    level = ("🔴 KRITIS" if composite >= 70 else
             "🟠 TINGGI" if composite >= 45 else
             "🟡 SEDANG" if composite >= 25 else
             "🟢 RENDAH")

    return {
        "composite_score": composite,
        "level":           level,
        "inventory_risk":  inv_risk,
        "demand_risk":     demand_risk,
        "coverage_risk":   cover_risk,
        "months_cover":    round(months_cover, 1),
    }


# ─────────────────────────────────────────────────────────────────
# MODUL 5: AI INSIGHT – CLAUDE API (UPGRADE: ganti Gemini)
# ─────────────────────────────────────────────────────────────────

def get_ai_recommendation(
    part_name: str,
    inventory_plan: dict,
    forecast_result: dict,
    risk_score: dict,
    current_stock: int,
    api_key: str = "",
) -> str:
    """
    [UPGRADE v2] Claude API (Anthropic) menggantikan Gemini.
    Prompt diperkaya dengan ABC-XYZ, Pareto, confidence interval forecast,
    dan analisis multi-dimensional risk.

    Install: pip install anthropic
    Set env: export ANTHROPIC_API_KEY=sk-ant-...
    """
    api_key = api_key or CFG.anthropic_api_key
    fc      = forecast_result["ensemble_forecast"]
    fc_vals = [round(v, 1) for v in fc.tolist()]
    lower   = [round(v, 1) for v in forecast_result["lower_bound"].tolist()]
    upper   = [round(v, 1) for v in forecast_result["upper_bound"].tolist()]

    prompt = f"""Kamu adalah NexusGen Supply Chain Oracle v2, AI advisor untuk manajemen suku cadang truk berat.
Analisis data ini dan berikan rekomendasi strategis dalam Bahasa Indonesia.

═══════ PROFIL SUKU CADANG ═══════
Nama Part        : {part_name}
Stok Saat Ini    : {current_stock} unit
Kritikalitas     : {inventory_plan['criticality']}
Kelas ABC        : {inventory_plan['abc_class']} (berdasarkan nilai inventori)
Kelas XYZ        : {inventory_plan['xyz_class']} (variabilitas demand: X=stabil, Y=sedang, Z=tidak menentu)
CV Demand        : {inventory_plan['cv']} (coefficient of variation)
Safety Stock     : {inventory_plan['safety_stock']} unit (dynamic, memperhitungkan variance lead time)
Reorder Point    : {inventory_plan['reorder_point']} unit
EOQ              : {inventory_plan['eoq']} unit
Service Level    : {inventory_plan['service_level_pct']}
Nilai Inventori  : Rp {inventory_plan['inventory_value_idr']:,}
Holding Cost/thn : Rp {inventory_plan['annual_holding_cost_idr']:,}

═══════ FORECAST {forecast_result['horizon']} BULAN ═══════
Metode           : {forecast_result['method']}
Proyeksi         : {fc_vals}
Batas Bawah (80%): {lower}
Batas Atas  (80%): {upper}
Croston Baseline : {forecast_result['croston_next']:.2f} unit/bulan

═══════ RISK SCORE MULTI-DIMENSI ═══════
Composite Score  : {risk_score['composite_score']}/100 ({risk_score['level']})
├─ Inventory Gap : {risk_score['inventory_risk']}/100
├─ Demand Uncert.: {risk_score['demand_risk']}/100
└─ Coverage Risk : {risk_score['coverage_risk']}/100
Sisa Stok Cover  : {risk_score['months_cover']} bulan

Format jawaban:
🎯 KEPUTUSAN UTAMA:
📊 ANALISIS (ABC-XYZ & risk breakdown):
⚡ TINDAKAN KONKRET (3 prioritas):
⚠️ RISIKO JIKA TIDAK BERTINDAK:
💡 REKOMENDASI JANGKA PANJANG:"""

    if not api_key:
        return _fallback_recommendation(part_name, inventory_plan, forecast_result,
                                         risk_score, current_stock)
    try:
        import urllib.request
        payload = {
            "model":      CFG.claude_model,
            "max_tokens": 1000,
            "messages":   [{"role": "user", "content": prompt}],
        }
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type":     "application/json",
                "x-api-key":        api_key,
                "anthropic-version": "2023-06-01",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
        return data["content"][0]["text"]
    except ImportError:
        print("⚠️  urllib tersedia, tapi parsing gagal.")
    except Exception as exc:
        print(f"⚠️  Claude API error: {exc}")

    return _fallback_recommendation(part_name, inventory_plan, forecast_result,
                                     risk_score, current_stock)


def _fallback_recommendation(
    part_name: str,
    inv: dict,
    fc: dict,
    risk: dict,
    current_stock: int,
) -> str:
    avg_fc = float(np.mean(fc["ensemble_forecast"]))
    months = risk["months_cover"]
    decision = (
        "🔴 PESAN DARURAT SEKARANG"  if current_stock <= 0 else
        "🔴 BELI SEKARANG"           if current_stock <= inv["safety_stock"] else
        "🟠 PESAN SEGERA"            if current_stock <= inv["reorder_point"] else
        "🟡 RENCANAKAN PO"           if months < 3 else
        "🟢 TAHAN STOK"
    )
    action = (
        f"Buat PO darurat {inv['eoq']} unit, prioritaskan pengiriman ekspres."
        if current_stock <= inv["reorder_point"] else
        f"Pantau harian; buat PO {inv['eoq']} unit saat stok = {inv['reorder_point']}."
    )
    return f"""🎯 KEPUTUSAN UTAMA: {decision}

📊 ANALISIS (ABC={inv['abc_class']}, XYZ={inv['xyz_class']}):
   Stok {current_stock} unit mencukupi ≈{months:.1f} bulan dengan forecast rata-rata {avg_fc:.1f} unit/bln.
   Risk Score {risk['composite_score']}/100 ({risk['level']}).
   CV={inv['cv']:.2f} menunjukkan demand {'stabil' if inv['xyz_class']=='X' else 'cukup bervariasi' if inv['xyz_class']=='Y' else 'sangat tidak menentu'}.

⚡ TINDAKAN KONKRET:
   1. {action}
   2. Konfirmasi lead time supplier ({inv['lead_time']} bulan) dan minta komitmen tertulis.
   3. Set alert otomatis di sistem WMS saat stok menyentuh ROP={inv['reorder_point']}.

⚠️ RISIKO JIKA TIDAK BERTINDAK:
   Downtime produksi akibat stockout {part_name} (criticality: {inv['criticality']}) dapat
   mengakibatkan kerugian produksi >> Rp {inv['unit_cost']:,} per insiden.

💡 REKOMENDASI JANGKA PANJANG:
   Part ABC={inv['abc_class']}/XYZ={inv['xyz_class']}: {'pertimbangkan VMI (vendor-managed inventory)' if inv['abc_class']=='A' else 'review safety stock setiap kuartal' if inv['abc_class']=='B' else 'konsolidasikan order dengan part C lainnya'}.
"""


# backward-compat: alias lama tetap berfungsi
def get_gemini_recommendation(part_name, croston, safety, lstm_forecasts,
                               current_stock, api_key=None):
    """Alias untuk kompatibilitas mundur. Sekarang memanggil Claude."""
    fc_arr = np.asarray(lstm_forecasts, dtype=float)
    mock_fc = {
        "ensemble_forecast": fc_arr,
        "lower_bound":       np.maximum(0, fc_arr * 0.7),
        "upper_bound":       fc_arr * 1.3,
        "croston_next":      croston.get("next_forecast", 0),
        "method":            "Legacy (via get_gemini_recommendation alias)",
        "horizon":           len(fc_arr),
    }
    mock_risk = {
        "composite_score": compute_risk_score(
            current_stock, safety, mock_fc)["composite_score"],
        "level": "", "inventory_risk": 0,
        "demand_risk": 0, "coverage_risk": 0, "months_cover": 0,
    }
    mock_risk.update(compute_risk_score(current_stock, safety, mock_fc))
    return get_ai_recommendation(part_name, safety, mock_fc, mock_risk,
                                  current_stock, api_key or "")


# ─────────────────────────────────────────────────────────────────
# MODUL 6: VISUALISASI DASHBOARD (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def visualize_nexusgen(
    df: pd.DataFrame,
    part_name: str,
    inventory_plan: dict,
    forecast_result: dict,
    risk_score: dict,
    all_results: dict,
    save_path: str = "nexusgen_dashboard_v2.png",
) -> str:
    """
    [UPGRADE v2] Dashboard 10 panel (v1: 4 panel).
    Panel baru: ABC analysis, Risk Matrix, Forecast CI, multi-part summary,
    Service Level scenario, XYZ distribution.
    """
    part_df = df[df["part_name"] == part_name].sort_values("date")
    dates   = part_df["date"].values
    demand  = part_df["demand"].values
    fc      = forecast_result["ensemble_forecast"]

    fig = plt.figure(figsize=(20, 14))
    fig.patch.set_facecolor("#0a0f1a")
    gs = gridspec.GridSpec(3, 4, figure=fig, hspace=0.50, wspace=0.38)

    C = {
        "blue":   "#4FC3F7", "green":  "#69F0AE", "red":    "#FF5252",
        "orange": "#FFB74D", "purple": "#CE93D8", "teal":   "#4DB6AC",
        "yellow": "#FFF176", "bg":     "#0d1420", "text":   "#E8EAF6",
        "border": "#1e2a3a",
    }

    def style(ax, title="", xlabel="", ylabel=""):
        ax.set_facecolor(C["bg"])
        ax.tick_params(colors=C["text"], labelsize=7.5)
        for sp in ax.spines.values():
            sp.set_edgecolor(C["border"])
        if title:
            ax.set_title(title, color=C["text"], fontsize=9, fontweight="bold", pad=5)
        if xlabel: ax.set_xlabel(xlabel, color=C["text"], fontsize=8)
        if ylabel: ax.set_ylabel(ylabel, color=C["text"], fontsize=8)

    # ── P1: Demand History ──
    ax1 = fig.add_subplot(gs[0, :2])
    style(ax1, f"📦 Demand Historis – {part_name}", ylabel="Qty")
    ax1.bar(range(len(demand)), demand, color=C["blue"], alpha=0.8, width=0.85)
    roll6 = pd.Series(demand).rolling(6, min_periods=1).mean().values
    ax1.plot(roll6, color=C["orange"], lw=1.5, label="Rolling 6-bln avg")
    ax1.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=8)

    # ── P2: Forecast dengan Confidence Interval (baru) ──
    ax2 = fig.add_subplot(gs[0, 2:])
    style(ax2, f"🔮 Forecast {forecast_result['horizon']} Bulan – {forecast_result['method'][:30]}",
          ylabel="Qty")
    last_n = min(12, len(demand))
    ax2.plot(range(last_n), demand[-last_n:], "o-", color=C["blue"],
             alpha=0.8, label="Aktual (12 bln terakhir)")
    x_fc = np.arange(last_n, last_n + len(fc))
    ax2.plot(x_fc, fc, "s--", color=C["green"], label="Forecast")
    ax2.fill_between(x_fc,
                     forecast_result["lower_bound"],
                     forecast_result["upper_bound"],
                     color=C["green"], alpha=0.15, label="80% CI")
    ax2.axhline(inventory_plan["safety_stock"],  color=C["red"],    ls=":", lw=1.2, label=f"SS={inventory_plan['safety_stock']}")
    ax2.axhline(inventory_plan["reorder_point"], color=C["orange"], ls=":", lw=1.2, label=f"ROP={inventory_plan['reorder_point']}")
    ax2.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    # ── P3: Inventory Plan (SS/ROP/EOQ) ──
    ax3 = fig.add_subplot(gs[1, 0])
    style(ax3, "📊 Inventory Plan")
    labels3 = ["Safety\nStock", "Reorder\nPoint", "EOQ"]
    vals3   = [inventory_plan["safety_stock"],
               inventory_plan["reorder_point"],
               inventory_plan["eoq"]]
    clrs3   = [C["red"], C["orange"], C["green"]]
    b3 = ax3.bar(labels3, vals3, color=clrs3, alpha=0.85)
    for bar, v in zip(b3, vals3):
        ax3.text(bar.get_x() + bar.get_width() / 2,
                 bar.get_height() + 0.2, f"{v}\nunit",
                 ha="center", color=C["text"], fontsize=8)

    # ── P4: Service Level Scenarios (baru) ──
    ax4 = fig.add_subplot(gs[1, 1])
    style(ax4, "Service Level Scenarios", ylabel="Safety Stock (unit)")
    part_info = SPARE_PARTS_CATALOG.get(part_name, {"unit_cost": 100_000, "criticality": "MEDIUM"})
    sc_dem = df[df["part_name"] == part_name]["demand"].values
    sls    = [90, 95, 97, 99]
    ss_vals = [calculate_safety_stock(sc_dem, unit_cost=part_info["unit_cost"],
                                       criticality=part_info["criticality"],
                                       service_level=sl/100)["safety_stock"]
               for sl in sls]
    ax4.plot(sls, ss_vals, "o-", color=C["purple"], lw=2)
    ax4.fill_between(sls, ss_vals, alpha=0.15, color=C["purple"])
    ax4.axvline(int(inventory_plan["service_level_pct"].rstrip("%")),
                color=C["yellow"], ls="--", lw=1.5, label="Current SL")
    ax4.set_xticks(sls)
    ax4.set_xticklabels([f"{s}%" for s in sls], color=C["text"])
    ax4.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    # ── P5: Risk Score Breakdown (baru) ──
    ax5 = fig.add_subplot(gs[1, 2])
    style(ax5, f"⚠️ Risk Score: {risk_score['composite_score']}/100 {risk_score['level']}")
    risk_cats = ["Inventory\nGap", "Demand\nUncert.", "Coverage\nRisk", "COMPOSITE"]
    risk_vals = [risk_score["inventory_risk"], risk_score["demand_risk"],
                 risk_score["coverage_risk"], risk_score["composite_score"]]
    clrs_risk = [C["red"] if v >= 70 else C["orange"] if v >= 45
                 else C["yellow"] if v >= 25 else C["green"]
                 for v in risk_vals]
    b5 = ax5.bar(risk_cats, risk_vals, color=clrs_risk, alpha=0.85)
    for bar, v in zip(b5, risk_vals):
        ax5.text(bar.get_x() + bar.get_width() / 2,
                 bar.get_height() + 1, f"{v}", ha="center",
                 color=C["text"], fontsize=8, fontweight="bold")
    ax5.set_ylim(0, 115)
    ax5.tick_params(axis="x", labelsize=7)

    # ── P6: ABC-XYZ Matrix (baru) ──
    ax6 = fig.add_subplot(gs[1, 3])
    style(ax6, "ABC-XYZ Classification")
    abc_xyz_counts: dict[str, int] = {}
    for pn, pdata in all_results.items():
        key = pdata["inv"]["abc_class"] + pdata["inv"]["xyz_class"]
        abc_xyz_counts[key] = abc_xyz_counts.get(key, 0) + 1
    if abc_xyz_counts:
        labels6 = list(abc_xyz_counts.keys())
        vals6   = list(abc_xyz_counts.values())
        clrs6   = [C["red"] if "A" in l else C["orange"] if "B" in l
                   else C["teal"] for l in labels6]
        ax6.pie(vals6, labels=labels6, colors=clrs6, autopct="%1.0f%%",
                textprops={"color": C["text"], "fontsize": 8})

    # ── P7: Multi-part Summary (baru) ──
    ax7 = fig.add_subplot(gs[2, :2])
    style(ax7, "📋 Ringkasan Semua Suku Cadang", ylabel="Unit")
    parts_list = list(all_results.keys())
    x7 = np.arange(len(parts_list))
    w7 = 0.25
    ss_all  = [all_results[p]["inv"]["safety_stock"]  for p in parts_list]
    rop_all = [all_results[p]["inv"]["reorder_point"] for p in parts_list]
    eoq_all = [all_results[p]["inv"]["eoq"]           for p in parts_list]
    ax7.bar(x7 - w7, ss_all,  w7, label="Safety Stock", color=C["red"],    alpha=0.8)
    ax7.bar(x7,      rop_all, w7, label="ROP",           color=C["orange"], alpha=0.8)
    ax7.bar(x7 + w7, eoq_all, w7, label="EOQ",           color=C["green"],  alpha=0.8)
    ax7.set_xticks(x7)
    ax7.set_xticklabels([p[:14] for p in parts_list], rotation=25,
                         ha="right", color=C["text"], fontsize=7)
    ax7.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    # ── P8: Forecast Comparison Croston vs Ensemble (baru) ──
    ax8 = fig.add_subplot(gs[2, 2:])
    style(ax8, "Croston Baseline vs Ensemble Forecast", ylabel="Qty/bulan")
    parts_short = [p[:14] for p in parts_list]
    croston_vals  = [all_results[p]["fc"]["croston_next"]           for p in parts_list]
    ensemble_avgs = [float(np.mean(all_results[p]["fc"]["ensemble_forecast"]))
                     for p in parts_list]
    x8 = np.arange(len(parts_list))
    ax8.bar(x8 - 0.2, croston_vals,  0.4, label="Croston",  color=C["blue"],  alpha=0.8)
    ax8.bar(x8 + 0.2, ensemble_avgs, 0.4, label="Ensemble", color=C["teal"],  alpha=0.8)
    ax8.set_xticks(x8)
    ax8.set_xticklabels(parts_short, rotation=25, ha="right",
                         color=C["text"], fontsize=7)
    ax8.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    fig.text(0.5, 0.985,
             "NexusGen v2.0 — Gen-AI Supply Chain Oracle",
             ha="center", color=C["text"], fontsize=14, fontweight="bold")
    fig.text(0.5, 0.968,
             "Astra UD Trucks | Prophet + HGB Ensemble · Dynamic SS (ABC-XYZ) · Claude AI · Risk Matrix",
             ha="center", color="#8899AA", fontsize=9)

    out = CFG.output_dir / save_path
    plt.savefig(str(out), dpi=140, bbox_inches="tight", facecolor="#0a0f1a")
    plt.close(fig)
    print(f"📊 Dashboard NexusGen v2.0 disimpan: {out}\n")
    return str(out)


# ─────────────────────────────────────────────────────────────────
# MODUL 7: EXPORT LAPORAN
# ─────────────────────────────────────────────────────────────────

def export_analysis_report(
    part_name: str,
    inventory_plan: dict,
    forecast_result: dict,
    risk_score: dict,
    ai_insight: str,
) -> Path:
    safe_name = part_name.replace(" ", "_").lower()
    path = CFG.output_dir / f"report_{safe_name}_v2.json"
    report = {
        "platform":   "NexusGen v2.0",
        "part_name":  part_name,
        "inventory":  {k: v for k, v in inventory_plan.items()},
        "forecast": {
            "method":   forecast_result["method"],
            "horizon":  forecast_result["horizon"],
            "values":   [round(v, 2) for v in forecast_result["ensemble_forecast"].tolist()],
            "lower":    [round(v, 2) for v in forecast_result["lower_bound"].tolist()],
            "upper":    [round(v, 2) for v in forecast_result["upper_bound"].tolist()],
            "croston_baseline": round(forecast_result["croston_next"], 2),
        },
        "risk_score": risk_score,
        "ai_insight": ai_insight,
    }
    with path.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    print(f"📁 Laporan disimpan: {path}")
    return path


# ─────────────────────────────────────────────────────────────────
# MODUL 8: PIPELINE UTAMA
# ─────────────────────────────────────────────────────────────────

def run_nexusgen_pipeline(
    selected_part: str = "Kampas Rem Besar",
    current_stock: int = 4,
    claude_api_key: str = "",
    export_reports: bool = True,
    save_visual: bool = True,
) -> dict:
    """
    Pipeline lengkap NexusGen v2.0:
    1.  Data 48 bulan, 8 parts, Negative Binomial
    2.  Forecast: Prophet + HGB ensemble (6 bulan, dengan CI)
    3.  Dynamic Safety Stock: ABC-XYZ + variance lead time
    4.  Risk Score multi-dimensi
    5.  Claude AI Insight (gantikan Gemini)
    6.  Dashboard 10 panel
    7.  JSON export per part
    """
    print("=" * 65)
    print("  NexusGen v2.0 – Gen-AI Supply Chain Oracle")
    print("  Astra UD Trucks | Prophet · HGB · ABC-XYZ · Claude AI")
    print("=" * 65 + "\n")

    # 1. Data
    print("📦 [1/5] Simulasi data demand (48 bln, 8 parts, Neg. Binomial)...")
    df = generate_intermittent_demand_data()

    # 2–4. Analisis semua parts
    print(f"🔍 [2/5] Menganalisis {len(SPARE_PARTS_CATALOG)} suku cadang...\n")
    all_results: dict[str, dict] = {}

    for pname, pinfo in SPARE_PARTS_CATALOG.items():
        print(f"  ▸ {pname}")
        p_demand = df[df["part_name"] == pname].sort_values("date")
        d_series = p_demand["demand"].values
        d_dates  = pd.DatetimeIndex(p_demand["date"].values)

        fc  = forecast_demand(d_series, d_dates)
        inv = calculate_safety_stock(d_series, part_name=pname,
                                      unit_cost=pinfo["unit_cost"],
                                      criticality=pinfo["criticality"])
        rs  = compute_risk_score(current_stock, inv, fc)
        all_results[pname] = {"fc": fc, "inv": inv, "risk": rs}

    print()

    # 5. Detail & AI untuk part yang dipilih
    profile = all_results[selected_part]
    fc_r    = profile["fc"]
    inv_r   = profile["inv"]
    risk_r  = profile["risk"]

    print(f"{'─'*60}")
    print(f"📋 DETAIL ANALISIS: {selected_part}")
    print(f"{'─'*60}")
    print(f"   ABC={inv_r['abc_class']} | XYZ={inv_r['xyz_class']} | "
          f"CV={inv_r['cv']} | Criticality={inv_r['criticality']}")
    print(f"   Safety Stock : {inv_r['safety_stock']} unit")
    print(f"   ROP          : {inv_r['reorder_point']} unit")
    print(f"   EOQ          : {inv_r['eoq']} unit")
    print(f"   Forecast 6 bln: {[round(v,1) for v in fc_r['ensemble_forecast'].tolist()]}")
    print(f"   Risk Score   : {risk_r['composite_score']}/100 ({risk_r['level']})")
    print(f"   Stok saat ini: {current_stock} unit | Cover: {risk_r['months_cover']} bln\n")

    print(f"{'─'*60}")
    print("🤖 [3/5] Meminta AI Insight dari Claude...")
    print(f"{'─'*60}")
    ai_insight = get_ai_recommendation(
        selected_part, inv_r, fc_r, risk_r, current_stock,
        api_key=claude_api_key,
    )
    print(ai_insight)

    # Summary tabel
    summary = pd.DataFrame([{
        "Suku Cadang": p,
        "ABC-XYZ":    v["inv"]["abc_class"] + v["inv"]["xyz_class"],
        "Forecast/Bln": round(float(np.mean(v["fc"]["ensemble_forecast"])), 1),
        "Safety Stock": v["inv"]["safety_stock"],
        "ROP":          v["inv"]["reorder_point"],
        "EOQ":          v["inv"]["eoq"],
        "Risk Score":   v["risk"]["composite_score"],
        "Risk Level":   v["risk"]["level"],
    } for p, v in all_results.items()])

    print(f"\n{'─'*60}")
    print("📊 [4/5] RINGKASAN SEMUA SUKU CADANG:")
    print(f"{'─'*60}")
    print(summary.to_string(index=False))

    # Dashboard & Export
    if save_visual:
        print(f"\n📈 [5/5] Membuat Dashboard (10 panel)...")
        visualize_nexusgen(df, selected_part, inv_r, fc_r,
                           risk_r, all_results)

    if export_reports:
        export_analysis_report(selected_part, inv_r, fc_r, risk_r, ai_insight)

    print("✅ NexusGen v2.0 Pipeline selesai!")

    return {
        "df":          df,
        "all_results": all_results,
        "selected":    selected_part,
        "fc":          fc_r,
        "inv":         inv_r,
        "risk":        risk_r,
        "ai_insight":  ai_insight,
        "summary":     summary,
    }


# ─────────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="NexusGen v2.0 – Gen-AI Supply Chain Oracle"
    )
    parser.add_argument("--part",    default="Kampas Rem Besar",
                        help="Nama suku cadang yang dianalisis detail")
    parser.add_argument("--stock",   type=int, default=4,
                        help="Stok aktual saat ini (unit)")
    parser.add_argument("--api-key", default="",
                        help="Anthropic (Claude) API Key")
    parser.add_argument("--no-save", action="store_true",
                        help="Jangan simpan laporan atau visualisasi")
    args = parser.parse_args(args=[])

    run_nexusgen_pipeline(
        selected_part=args.part,
        current_stock=args.stock,
        claude_api_key=args.api_key,
        export_reports=not args.no_save,
        save_visual=not args.no_save,
    )